### ISSUE TITLE
difficulty table ?

### ISSUE THREAD

**Issue by terefang** [PeterRudin-Burgess/Bare-Metal-Edition#3]
have i overlooked somthing or is there no classic difficulty table ?

| Difficulty | Modifier |
| -- | -- |
| Casual | +70|
| Simple | +50|
| Routine | +30 |
|  Easy | +20|
|  Light | +10|
|  Medium | +0 |
| Hard | -10|
|Very Hard | -20|
| Extremely Hard | -30|
| Sheer Folly | -50|
| Absurd | -70 |
| Nigh Impossible | -100 |

**Comment by PeterRudin-Burgess** [comment]
You haven't overlooked it, it doesn't exist for a few reasons.
1) Digital vs. Analogue.
As soon as you start defining explicit levels of difficulty, you have a digital system where something is either Extremely hard or Sheer Folly. Having that in a table implies that -60 is not an option. Not having the table but explaining the GM that they can set penalties to reflect the difficulty empowers the GM. It also means for high powered games with very high-level characters with really high bonuses, the GM can continue to challenge them. They just scale up the penalties.
Having an explicit difficulty table means min/max players will think "I only need x ranks in this skill to ensure I pass the test nearly every time."

2) One Less Table
One of the criticisms of all brands of Rolemaster was too many tables. Giving the GM the freedom to set difficulty modifiers as they see fit removes a table. The only skill table in the book is the percentage manoeuvre table and that is optional.

3) No Rolls for Routine or Easy Tasks
I am very opposed to having characters roll skill tests for medium or better difficulty tasks. I can see the logic that if harder tasks have penalties then easier tasks should have bonuses. But, it has got lost somewhere along the way that you should not be rolling at all unless the test is of vital importance and the consequences unknown and have implications for the story of the characters. The math also makes a nonsense of rolling for easy tasks. 
Vienna Airport has about 200 landings and takeoffs per day. 1 in 20 pilot rolls would be an open-ended downwards result. Maybe a near miss or some other pilot error. Once every two days would be a double open-ended downwards roll, That must be a much more serious error. Every seven weeks would be a triple open-ended downwards. Once every three years, there would be a quadruple open-ended downward roll. Vienna airport would be just a smoking crater in the ground and most of Vienna would be rubble. This is, of course, assuming that every landing was routine. If the weather was bad of they landed during the night, the death toll would be much higher.

For all these reasons I want to leave the difficulty modifiers as a paragraph of text, rather than a table. A mix of design philosophy, old school play style and empowering the GM.

**Comment by terefang** [comment]
ok .. too crunchy
